"""v1 multitenant business automation

Revision ID: 0a418fe81167
Revises: 4db4cfcb30fe
Create Date: 2026-08-05 17:25:32.899985
"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

revision: str = "0a418fe81167"
down_revision: str | Sequence[str] | None = "4db4cfcb30fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

DEFAULT_ORG_ID = "00000000-0000-0000-0000-000000000001"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """Применить this Alembic revision in dependency-safe schema order."""
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "SUSPENDED",
                "ARCHIVED",
                name="organizationstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("timezone_name", sa.String(length=80), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("ai_enabled", sa.Boolean(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_organizations_slug"), ["slug"], unique=True)
        batch_op.create_index(batch_op.f("ix_organizations_status"), ["status"], unique=False)

    now = datetime.now(UTC)
    op.bulk_insert(
        sa.table(
            "organizations",
            sa.column("id", sa.String()),
            sa.column("name", sa.String()),
            sa.column("slug", sa.String()),
            sa.column("status", sa.String()),
            sa.column("timezone_name", sa.String()),
            sa.column("retention_days", sa.Integer()),
            sa.column("ai_enabled", sa.Boolean()),
            sa.column("settings", sa.JSON()),
            sa.column("created_at", sa.DateTime(timezone=True)),
            sa.column("updated_at", sa.DateTime(timezone=True)),
        ),
        [
            {
                "id": DEFAULT_ORG_ID,
                "name": "Основная организация",
                "slug": "main",
                "status": "ACTIVE",
                "timezone_name": "Europe/Helsinki",
                "retention_days": 90,
                "ai_enabled": False,
                "settings": {},
                "created_at": now,
                "updated_at": now,
            }
        ],
    )

    op.create_table(
        "outbox_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.String(length=80), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("target_endpoint_ids", sa.JSON(), nullable=True),
        sa.Column("delivery_state", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "RETRY",
                "DELIVERED",
                "FAILED",
                "DEAD",
                name="outboxstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=120), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("outbox_events", schema=None) as batch_op:
        batch_op.create_index("ix_outbox_due_status", ["status", "due_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_outbox_events_aggregate_id"), ["aggregate_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_outbox_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_outbox_events_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_outbox_events_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_outbox_org_created", ["organization_id", "created_at"], unique=False
        )

    op.create_table(
        "ai_provider_configs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=140), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "DISABLED",
                "RULE_BASED",
                "OPENAI_COMPATIBLE",
                name="aiproviderkind",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("base_url", sa.String(length=1000), nullable=True),
        sa.Column("model_name", sa.String(length=160), nullable=True),
        sa.Column("api_key_enc", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("max_output_tokens", sa.Integer(), nullable=False),
        sa.Column("temperature_milli", sa.Integer(), nullable=False),
        sa.Column("data_region", sa.String(length=80), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("allowed_models", sa.JSON(), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_ai_provider_org_name"),
    )
    with op.batch_alter_table("ai_provider_configs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_provider_configs_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("key_prefix", sa.String(length=20), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "REVOKED", "EXPIRED", name="apikeystatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("secret_hash", name="uq_api_key_secret_hash"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index("ix_api_key_org_status", ["organization_id", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_keys_key_prefix"), ["key_prefix"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_api_keys_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "integration_endpoints",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "WEBHOOK",
                "GOOGLE_SHEETS",
                "CSV_EXPORT",
                name="integrationkind",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("config_enc", sa.Text(), nullable=True),
        sa.Column("event_types", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_integration_org_name"),
    )
    with op.batch_alter_table("integration_endpoints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_integration_endpoints_organization_id"),
            ["organization_id"],
            unique=False,
        )

    op.create_table(
        "knowledge_base_articles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("vacancy_key", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("knowledge_base_articles", schema=None) as batch_op:
        batch_op.create_index(
            "ix_kb_org_active_vacancy",
            ["organization_id", "is_active", "vacancy_key"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_knowledge_base_articles_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_knowledge_base_articles_vacancy_key"), ["vacancy_key"], unique=False
        )

    op.create_table(
        "automation_policies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("telegram_connection_id", sa.String(length=36), nullable=False),
        sa.Column("ai_provider_config_id", sa.String(length=36), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("timezone_name", sa.String(length=80), nullable=False),
        sa.Column("active_hours", sa.JSON(), nullable=False),
        sa.Column("allowed_chat_types", sa.JSON(), nullable=False),
        sa.Column("consent_notice", sa.Text(), nullable=False),
        sa.Column("fallback_message", sa.Text(), nullable=False),
        sa.Column("max_auto_replies_per_day", sa.Integer(), nullable=False),
        sa.Column("require_consent_before_ai", sa.Boolean(), nullable=False),
        sa.Column("handoff_keywords", sa.JSON(), nullable=False),
        sa.Column("stop_words", sa.JSON(), nullable=False),
        sa.Column("vacancy_detection_rules", sa.JSON(), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ai_provider_config_id"], ["ai_provider_configs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["telegram_connection_id"], ["telegram_connections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_policy_org_name"),
    )
    with op.batch_alter_table("automation_policies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_automation_policies_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_automation_policies_telegram_connection_id"),
            ["telegram_connection_id"],
            unique=False,
        )

    op.create_table(
        "inbound_telegram_updates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("telegram_connection_id", sa.String(length=36), nullable=False),
        sa.Column("telegram_update_id", sa.BigInteger(), nullable=False),
        sa.Column("update_type", sa.String(length=80), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "PROCESSED",
                "IGNORED",
                "FAILED",
                name="inboundupdatestatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("payload_redacted", sa.JSON(), nullable=False),
        sa.Column("payload_enc", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["telegram_connection_id"], ["telegram_connections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "telegram_connection_id", "telegram_update_id", name="uq_connection_update_id"
        ),
    )
    with op.batch_alter_table("inbound_telegram_updates", schema=None) as batch_op:
        batch_op.create_index(
            "ix_inbound_org_status_received",
            ["organization_id", "status", "received_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inbound_telegram_updates_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inbound_telegram_updates_telegram_connection_id"),
            ["telegram_connection_id"],
            unique=False,
        )

    op.create_table(
        "telegram_business_connections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("telegram_connection_id", sa.String(length=36), nullable=False),
        sa.Column("business_connection_id", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "DISCONNECTED",
                "REVOKED",
                name="businessconnectionstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("user_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=80), nullable=True),
        sa.Column("last_name", sa.String(length=80), nullable=True),
        sa.Column("rights", sa.JSON(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disconnected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_update_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["telegram_connection_id"], ["telegram_connections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "telegram_connection_id", "business_connection_id", name="uq_bot_business_connection"
        ),
    )
    with op.batch_alter_table("telegram_business_connections", schema=None) as batch_op:
        batch_op.create_index("ix_business_org_status", ["organization_id", "status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_telegram_business_connections_business_connection_id"),
            ["business_connection_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_telegram_business_connections_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_telegram_business_connections_telegram_connection_id"),
            ["telegram_connection_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_telegram_business_connections_telegram_user_id"),
            ["telegram_user_id"],
            unique=False,
        )

    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("business_connection_id", sa.String(length=36), nullable=False),
        sa.Column("automation_policy_id", sa.String(length=36), nullable=True),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=80), nullable=True),
        sa.Column("last_name", sa.String(length=80), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "AWAITING_CONSENT",
                "AI_ACTIVE",
                "HUMAN_HANDOFF",
                "CLOSED",
                "BLOCKED",
                name="conversationstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "consent_status",
            sa.Enum(
                "UNKNOWN",
                "REQUESTED",
                "GRANTED",
                "DECLINED",
                "REVOKED",
                name="consentstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consent_notice_version", sa.String(length=40), nullable=True),
        sa.Column("source_campaign_id", sa.String(length=36), nullable=True),
        sa.Column("vacancy_key", sa.String(length=120), nullable=True),
        sa.Column("assigned_user_id", sa.String(length=36), nullable=True),
        sa.Column("ai_enabled", sa.Boolean(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_inbound_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_outbound_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["automation_policy_id"], ["automation_policies.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["business_connection_id"], ["telegram_business_connections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_campaign_id"],
            ["campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_connection_id", "telegram_chat_id", name="uq_business_conversation_chat"
        ),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_conversation_org_status_last",
            ["organization_id", "status", "last_message_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_assigned_user_id"), ["assigned_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_business_connection_id"),
            ["business_connection_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_last_message_at"), ["last_message_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_retention_until"), ["retention_until"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_conversations_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_conversations_telegram_chat_id"), ["telegram_chat_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_telegram_user_id"), ["telegram_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_vacancy_key"), ["vacancy_key"], unique=False
        )

    op.create_table(
        "candidate_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("full_name", sa.String(length=180), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("experience", sa.Text(), nullable=True),
        sa.Column("schedule", sa.String(length=250), nullable=True),
        sa.Column("phone_enc", sa.Text(), nullable=True),
        sa.Column("email_enc", sa.Text(), nullable=True),
        sa.Column("vacancy_key", sa.String(length=120), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "QUALIFYING",
                "READY_FOR_REVIEW",
                "CONTACTED",
                "ARCHIVED",
                name="candidatestatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("structured_data", sa.JSON(), nullable=False),
        sa.Column("consent_to_storage", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", name="uq_candidate_conversation"),
    )
    with op.batch_alter_table("candidate_profiles", schema=None) as batch_op:
        batch_op.create_index(
            "ix_candidate_org_status", ["organization_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_candidate_profiles_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_candidate_profiles_vacancy_key"), ["vacancy_key"], unique=False
        )

    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "direction",
            sa.Enum(
                "INBOUND",
                "OUTBOUND",
                "SYSTEM",
                name="messagedirection",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "author",
            sa.Enum(
                "CONTACT",
                "BUSINESS_USER",
                "ASSISTANT",
                "OPERATOR",
                "SYSTEM",
                name="messageauthor",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("body_enc", sa.Text(), nullable=True),
        sa.Column("body_preview", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=40), nullable=False),
        sa.Column("reply_to_message_id", sa.BigInteger(), nullable=True),
        sa.Column("ai_processed", sa.Boolean(), nullable=False),
        sa.Column("raw_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "conversation_id",
            "telegram_message_id",
            "direction",
            name="uq_conversation_message_direction",
        ),
    )
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_messages_conversation_id"),
            ["conversation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_conversation_messages_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversation_messages_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_message_org_conversation_created",
            ["organization_id", "conversation_id", "created_at"],
            unique=False,
        )

    op.create_table(
        "privacy_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column(
            "request_type",
            sa.Enum("EXPORT", "DELETE", name="privacyrequesttype", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="privacyrequeststatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("conversation_id", sa.String(length=36), nullable=True),
        sa.Column("requested_by_id", sa.String(length=36), nullable=False),
        sa.Column("output_relative_path", sa.String(length=1000), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("privacy_requests", schema=None) as batch_op:
        batch_op.create_index(
            "ix_privacy_org_status_created",
            ["organization_id", "status", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_privacy_requests_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_privacy_requests_telegram_chat_id"), ["telegram_chat_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_privacy_requests_telegram_user_id"), ["telegram_user_id"], unique=False
        )

    op.create_table(
        "ai_interactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("source_message_id", sa.String(length=36), nullable=True),
        sa.Column("provider_config_id", sa.String(length=36), nullable=True),
        sa.Column("provider_kind", sa.String(length=40), nullable=False),
        sa.Column("model_name", sa.String(length=160), nullable=True),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("prompt_preview", sa.Text(), nullable=False),
        sa.Column("response_preview", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SUCCEEDED",
                "BLOCKED",
                "FAILED",
                "SKIPPED",
                name="aiinteractionstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("safety_flags", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["provider_config_id"], ["ai_provider_configs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"], ["conversation_messages.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_interactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_interactions_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ai_interactions_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ai_interactions_request_hash"), ["request_hash"], unique=False
        )
        batch_op.create_index(
            "ix_ai_org_created_status", ["organization_id", "created_at", "status"], unique=False
        )

    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "organization_id",
                sa.String(length=36),
                server_default=DEFAULT_ORG_ID,
                nullable=True,
            )
        )
        batch_op.drop_index(batch_op.f("ix_audit_created_action"))
        batch_op.create_index(
            batch_op.f("ix_audit_logs_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            "ix_audit_org_created_action", ["organization_id", "created_at", "action"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_audit_logs_organization_id_organizations",
            "organizations",
            ["organization_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("campaign_destinations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "organization_id",
                sa.String(length=36),
                server_default=DEFAULT_ORG_ID,
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_campaign_destinations_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_campaign_destinations_organization_id_organizations",
            "organizations",
            ["organization_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("campaign_runs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "organization_id",
                sa.String(length=36),
                server_default=DEFAULT_ORG_ID,
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_campaign_runs_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_campaign_runs_organization_id_organizations",
            "organizations",
            ["organization_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "organization_id",
                sa.String(length=36),
                server_default=DEFAULT_ORG_ID,
                nullable=False,
            )
        )
        batch_op.drop_index(batch_op.f("ix_campaign_due"))
        batch_op.create_index(
            "ix_campaign_org_due", ["organization_id", "status", "next_run_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_campaigns_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_campaigns_organization_id_organizations",
            "organizations",
            ["organization_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("delivery_jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "organization_id",
                sa.String(length=36),
                server_default=DEFAULT_ORG_ID,
                nullable=False,
            )
        )
        batch_op.drop_index(batch_op.f("ix_delivery_due_status"))
        batch_op.create_index(
            batch_op.f("ix_delivery_jobs_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            "ix_delivery_org_due_status", ["organization_id", "status", "due_at"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_delivery_jobs_organization_id_organizations",
            "organizations",
            ["organization_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("destinations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "organization_id",
                sa.String(length=36),
                server_default=DEFAULT_ORG_ID,
                nullable=False,
            )
        )
        batch_op.drop_index(batch_op.f("ix_destination_enabled_permission"))
        batch_op.create_index(
            "ix_destination_org_enabled_permission",
            ["organization_id", "enabled", "permission_status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_destinations_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_destinations_organization_id_organizations",
            "organizations",
            ["organization_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("media_assets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "organization_id",
                sa.String(length=36),
                server_default=DEFAULT_ORG_ID,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "storage_backend", sa.String(length=20), server_default="local", nullable=False
            )
        )
        batch_op.add_column(sa.Column("storage_key", sa.String(length=1000), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_media_assets_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_unique_constraint(
            "uq_media_org_stored_name", ["organization_id", "stored_name"]
        )
        batch_op.create_foreign_key(
            "fk_media_assets_organization_id_organizations",
            "organizations",
            ["organization_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("message_templates", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "organization_id",
                sa.String(length=36),
                server_default=DEFAULT_ORG_ID,
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_message_templates_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_message_templates_organization_id_organizations",
            "organizations",
            ["organization_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("telegram_auth_challenges", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "organization_id",
                sa.String(length=36),
                server_default=DEFAULT_ORG_ID,
                nullable=False,
            )
        )
        batch_op.alter_column("payload_enc", existing_type=sa.TEXT(), nullable=True)
        batch_op.create_index(
            batch_op.f("ix_telegram_auth_challenges_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_telegram_auth_challenges_organization_id_organizations",
            "organizations",
            ["organization_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("telegram_connections", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "organization_id",
                sa.String(length=36),
                server_default=DEFAULT_ORG_ID,
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_telegram_connections_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_unique_constraint("uq_connection_org_name", ["organization_id", "name"])
        batch_op.create_foreign_key(
            "fk_telegram_connections_organization_id_organizations",
            "organizations",
            ["organization_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "organization_id",
                sa.String(length=36),
                server_default=DEFAULT_ORG_ID,
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_users_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_unique_constraint("uq_user_org_email", ["organization_id", "email"])
        batch_op.create_foreign_key(
            "fk_users_organization_id_organizations",
            "organizations",
            ["organization_id"],
            ["id"],
            ondelete="CASCADE",
        )

    op.execute(
        sa.text("UPDATE media_assets SET storage_key = relative_path WHERE storage_key IS NULL")
    )
    for table_name in (
        "audit_logs",
        "campaign_destinations",
        "campaign_runs",
        "campaigns",
        "delivery_jobs",
        "destinations",
        "media_assets",
        "message_templates",
        "telegram_auth_challenges",
        "telegram_connections",
        "users",
    ):
        with op.batch_alter_table(table_name, schema=None) as batch_op:
            batch_op.alter_column("organization_id", server_default=None)
    with op.batch_alter_table("media_assets", schema=None) as batch_op:
        batch_op.alter_column("storage_backend", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """Откатить this Alembic revision in dependency-safe schema order."""
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("fk_users_organization_id_organizations", type_="foreignkey")
        batch_op.drop_constraint("uq_user_org_email", type_="unique")
        batch_op.drop_index(batch_op.f("ix_users_organization_id"))
        batch_op.drop_column("organization_id")

    with op.batch_alter_table("telegram_connections", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_telegram_connections_organization_id_organizations", type_="foreignkey"
        )
        batch_op.drop_constraint("uq_connection_org_name", type_="unique")
        batch_op.drop_index(batch_op.f("ix_telegram_connections_organization_id"))
        batch_op.drop_column("organization_id")

    with op.batch_alter_table("telegram_auth_challenges", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_telegram_auth_challenges_organization_id_organizations", type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_telegram_auth_challenges_organization_id"))
        batch_op.alter_column("payload_enc", existing_type=sa.TEXT(), nullable=False)
        batch_op.drop_column("organization_id")

    with op.batch_alter_table("message_templates", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_message_templates_organization_id_organizations", type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_message_templates_organization_id"))
        batch_op.drop_column("organization_id")

    with op.batch_alter_table("media_assets", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_media_assets_organization_id_organizations", type_="foreignkey"
        )
        batch_op.drop_constraint("uq_media_org_stored_name", type_="unique")
        batch_op.drop_index(batch_op.f("ix_media_assets_organization_id"))
        batch_op.drop_column("storage_key")
        batch_op.drop_column("storage_backend")
        batch_op.drop_column("organization_id")

    with op.batch_alter_table("destinations", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_destinations_organization_id_organizations", type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_destinations_organization_id"))
        batch_op.drop_index("ix_destination_org_enabled_permission")
        batch_op.create_index(
            batch_op.f("ix_destination_enabled_permission"),
            ["enabled", "permission_status"],
            unique=False,
        )
        batch_op.drop_column("organization_id")

    with op.batch_alter_table("delivery_jobs", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_delivery_jobs_organization_id_organizations", type_="foreignkey"
        )
        batch_op.drop_index("ix_delivery_org_due_status")
        batch_op.drop_index(batch_op.f("ix_delivery_jobs_organization_id"))
        batch_op.create_index(
            batch_op.f("ix_delivery_due_status"), ["status", "due_at"], unique=False
        )
        batch_op.drop_column("organization_id")

    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.drop_constraint("fk_campaigns_organization_id_organizations", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_campaigns_organization_id"))
        batch_op.drop_index("ix_campaign_org_due")
        batch_op.create_index(
            batch_op.f("ix_campaign_due"), ["status", "next_run_at"], unique=False
        )
        batch_op.drop_column("organization_id")

    with op.batch_alter_table("campaign_runs", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_campaign_runs_organization_id_organizations", type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_campaign_runs_organization_id"))
        batch_op.drop_column("organization_id")

    with op.batch_alter_table("campaign_destinations", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_campaign_destinations_organization_id_organizations", type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_campaign_destinations_organization_id"))
        batch_op.drop_column("organization_id")

    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_audit_logs_organization_id_organizations", type_="foreignkey")
        batch_op.drop_index("ix_audit_org_created_action")
        batch_op.drop_index(batch_op.f("ix_audit_logs_organization_id"))
        batch_op.create_index(
            batch_op.f("ix_audit_created_action"), ["created_at", "action"], unique=False
        )
        batch_op.drop_column("organization_id")

    with op.batch_alter_table("ai_interactions", schema=None) as batch_op:
        batch_op.drop_index("ix_ai_org_created_status")
        batch_op.drop_index(batch_op.f("ix_ai_interactions_request_hash"))
        batch_op.drop_index(batch_op.f("ix_ai_interactions_organization_id"))
        batch_op.drop_index(batch_op.f("ix_ai_interactions_conversation_id"))

    op.drop_table("ai_interactions")
    with op.batch_alter_table("privacy_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_privacy_requests_telegram_user_id"))
        batch_op.drop_index(batch_op.f("ix_privacy_requests_telegram_chat_id"))
        batch_op.drop_index(batch_op.f("ix_privacy_requests_organization_id"))
        batch_op.drop_index("ix_privacy_org_status_created")

    op.drop_table("privacy_requests")
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.drop_index("ix_message_org_conversation_created")
        batch_op.drop_index(batch_op.f("ix_conversation_messages_organization_id"))
        batch_op.drop_index(batch_op.f("ix_conversation_messages_created_at"))
        batch_op.drop_index(batch_op.f("ix_conversation_messages_conversation_id"))

    op.drop_table("conversation_messages")
    with op.batch_alter_table("candidate_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_profiles_vacancy_key"))
        batch_op.drop_index(batch_op.f("ix_candidate_profiles_organization_id"))
        batch_op.drop_index("ix_candidate_org_status")

    op.drop_table("candidate_profiles")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_vacancy_key"))
        batch_op.drop_index(batch_op.f("ix_conversations_telegram_user_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_telegram_chat_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_status"))
        batch_op.drop_index(batch_op.f("ix_conversations_retention_until"))
        batch_op.drop_index(batch_op.f("ix_conversations_organization_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_last_message_at"))
        batch_op.drop_index(batch_op.f("ix_conversations_business_connection_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_assigned_user_id"))
        batch_op.drop_index("ix_conversation_org_status_last")

    op.drop_table("conversations")
    with op.batch_alter_table("telegram_business_connections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_telegram_business_connections_telegram_user_id"))
        batch_op.drop_index(batch_op.f("ix_telegram_business_connections_telegram_connection_id"))
        batch_op.drop_index(batch_op.f("ix_telegram_business_connections_organization_id"))
        batch_op.drop_index(batch_op.f("ix_telegram_business_connections_business_connection_id"))
        batch_op.drop_index("ix_business_org_status")

    op.drop_table("telegram_business_connections")
    with op.batch_alter_table("inbound_telegram_updates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inbound_telegram_updates_telegram_connection_id"))
        batch_op.drop_index(batch_op.f("ix_inbound_telegram_updates_organization_id"))
        batch_op.drop_index("ix_inbound_org_status_received")

    op.drop_table("inbound_telegram_updates")
    with op.batch_alter_table("automation_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_automation_policies_telegram_connection_id"))
        batch_op.drop_index(batch_op.f("ix_automation_policies_organization_id"))

    op.drop_table("automation_policies")
    with op.batch_alter_table("knowledge_base_articles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_base_articles_vacancy_key"))
        batch_op.drop_index(batch_op.f("ix_knowledge_base_articles_organization_id"))
        batch_op.drop_index("ix_kb_org_active_vacancy")

    op.drop_table("knowledge_base_articles")
    with op.batch_alter_table("integration_endpoints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_integration_endpoints_organization_id"))

    op.drop_table("integration_endpoints")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_organization_id"))
        batch_op.drop_index(batch_op.f("ix_api_keys_key_prefix"))
        batch_op.drop_index("ix_api_key_org_status")

    op.drop_table("api_keys")
    with op.batch_alter_table("ai_provider_configs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_provider_configs_organization_id"))

    op.drop_table("ai_provider_configs")
    with op.batch_alter_table("outbox_events", schema=None) as batch_op:
        batch_op.drop_index("ix_outbox_org_created")
        batch_op.drop_index(batch_op.f("ix_outbox_events_status"))
        batch_op.drop_index(batch_op.f("ix_outbox_events_organization_id"))
        batch_op.drop_index(batch_op.f("ix_outbox_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_outbox_events_aggregate_id"))
        batch_op.drop_index("ix_outbox_due_status")

    op.drop_table("outbox_events")
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_status"))
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))

    op.drop_table("organizations")
    # ### end Alembic commands ###
