"""v1.6 commissioning and portability

Revision ID: 2a6f0104062a
Revises: e2f4a6c8d0b1
Create Date: 2026-08-06 10:03:53.857800
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2a6f0104062a"
down_revision: str | Sequence[str] | None = "e2f4a6c8d0b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """Применить this Alembic revision in dependency-safe schema order."""
    op.create_table(
        "commissioning_check_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PASSED", "WARNING", "BLOCKED", name="readinessstatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("checks", sa.JSON(), nullable=False),
        sa.Column("blockers", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("commissioning_check_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_commissioning_check_runs_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_commissioning_check_runs_fingerprint"), ["fingerprint"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_commissioning_check_runs_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_commissioning_check_runs_status"), ["status"], unique=False
        )
        batch_op.create_index(
            "ix_commissioning_org_created", ["organization_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_commissioning_org_status_expires",
            ["organization_id", "status", "expires_at"],
            unique=False,
        )

    op.create_table(
        "configuration_bundles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "EXPORT", "IMPORT", name="configurationbundlekind", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "READY",
                "IMPORTED",
                "FAILED",
                name="configurationbundlestatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("source_product_version", sa.String(length=40), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=1000), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("include_media", sa.Boolean(), nullable=False),
        sa.Column("conflict_mode", sa.String(length=20), nullable=True),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("applied_by_id", sa.String(length=36), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["applied_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("configuration_bundles", schema=None) as batch_op:
        batch_op.create_index(
            "ix_configuration_bundle_org_created", ["organization_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_configuration_bundle_org_kind_status",
            ["organization_id", "kind", "status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_configuration_bundles_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_configuration_bundles_sha256"), ["sha256"], unique=False
        )

    op.create_table(
        "pilot_programs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "PAUSED",
                "COMPLETED",
                "CANCELLED",
                name="pilotprogramstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("stage_sizes", sa.JSON(), nullable=False),
        sa.Column("current_stage_order", sa.Integer(), nullable=False),
        sa.Column("require_distinct_signoff", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pilot_programs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_pilot_program_org_campaign", ["organization_id", "campaign_id"], unique=False
        )
        batch_op.create_index(
            "ix_pilot_program_org_status", ["organization_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_pilot_programs_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_pilot_programs_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_pilot_programs_status"), ["status"], unique=False)

    op.create_table(
        "pilot_stage_executions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("program_id", sa.String(length=36), nullable=False),
        sa.Column("stage_order", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("target_destination_count", sa.Integer(), nullable=False),
        sa.Column("requires_live_telegram", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "READY",
                "RUNNING",
                "AWAITING_SIGNOFF",
                "PASSED",
                "FAILED",
                "SKIPPED",
                name="pilotstagestatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("commissioning_check_id", sa.String(length=36), nullable=True),
        sa.Column("readiness_report_id", sa.String(length=36), nullable=True),
        sa.Column("preflight_report_id", sa.String(length=36), nullable=True),
        sa.Column("campaign_run_id", sa.String(length=36), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("evidence_sha256", sa.String(length=64), nullable=True),
        sa.Column("started_by_id", sa.String(length=36), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signed_off_by_id", sa.String(length=36), nullable=True),
        sa.Column("signed_off_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signoff_note", sa.Text(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["campaign_run_id"], ["campaign_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["commissioning_check_id"], ["commissioning_check_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["preflight_report_id"], ["campaign_preflight_reports.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["program_id"], ["pilot_programs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["readiness_report_id"], ["pilot_readiness_reports.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["signed_off_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["started_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("program_id", "stage_order", name="uq_pilot_program_stage_order"),
    )
    with op.batch_alter_table("pilot_stage_executions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pilot_stage_executions_campaign_run_id"),
            ["campaign_run_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_pilot_stage_executions_commissioning_check_id"),
            ["commissioning_check_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_pilot_stage_executions_evidence_sha256"),
            ["evidence_sha256"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_pilot_stage_executions_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_pilot_stage_executions_preflight_report_id"),
            ["preflight_report_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_pilot_stage_executions_program_id"), ["program_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_pilot_stage_executions_readiness_report_id"),
            ["readiness_report_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_pilot_stage_executions_status"), ["status"], unique=False
        )
        batch_op.create_index(
            "ix_pilot_stage_org_status", ["organization_id", "status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """Откатить this Alembic revision in dependency-safe schema order."""
    with op.batch_alter_table("pilot_stage_executions", schema=None) as batch_op:
        batch_op.drop_index("ix_pilot_stage_org_status")
        batch_op.drop_index(batch_op.f("ix_pilot_stage_executions_status"))
        batch_op.drop_index(batch_op.f("ix_pilot_stage_executions_readiness_report_id"))
        batch_op.drop_index(batch_op.f("ix_pilot_stage_executions_program_id"))
        batch_op.drop_index(batch_op.f("ix_pilot_stage_executions_preflight_report_id"))
        batch_op.drop_index(batch_op.f("ix_pilot_stage_executions_organization_id"))
        batch_op.drop_index(batch_op.f("ix_pilot_stage_executions_evidence_sha256"))
        batch_op.drop_index(batch_op.f("ix_pilot_stage_executions_commissioning_check_id"))
        batch_op.drop_index(batch_op.f("ix_pilot_stage_executions_campaign_run_id"))

    op.drop_table("pilot_stage_executions")
    with op.batch_alter_table("pilot_programs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pilot_programs_status"))
        batch_op.drop_index(batch_op.f("ix_pilot_programs_organization_id"))
        batch_op.drop_index(batch_op.f("ix_pilot_programs_campaign_id"))
        batch_op.drop_index("ix_pilot_program_org_status")
        batch_op.drop_index("ix_pilot_program_org_campaign")

    op.drop_table("pilot_programs")
    with op.batch_alter_table("configuration_bundles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_configuration_bundles_sha256"))
        batch_op.drop_index(batch_op.f("ix_configuration_bundles_organization_id"))
        batch_op.drop_index("ix_configuration_bundle_org_kind_status")
        batch_op.drop_index("ix_configuration_bundle_org_created")

    op.drop_table("configuration_bundles")
    with op.batch_alter_table("commissioning_check_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_commissioning_org_status_expires")
        batch_op.drop_index("ix_commissioning_org_created")
        batch_op.drop_index(batch_op.f("ix_commissioning_check_runs_status"))
        batch_op.drop_index(batch_op.f("ix_commissioning_check_runs_organization_id"))
        batch_op.drop_index(batch_op.f("ix_commissioning_check_runs_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_commissioning_check_runs_expires_at"))

    op.drop_table("commissioning_check_runs")
    # ### end Alembic commands ###
