"""initial schema

Revision ID: 4db4cfcb30fe
Revises:
Create Date: 2026-08-05 15:34:18.507277
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4db4cfcb30fe"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """Применить this Alembic revision in dependency-safe schema order."""
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER",
                "ADMIN",
                "OPERATOR",
                "VIEWER",
                name="userrole",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("totp_secret_enc", sa.Text(), nullable=True),
        sa.Column("pending_totp_secret_enc", sa.Text(), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "worker_heartbeats",
        sa.Column("worker_id", sa.String(length=120), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("worker_id"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=True),
        sa.Column("entity_id", sa.String(length=80), nullable=True),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO", "WARNING", "CRITICAL", name="safetyseverity", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index("ix_audit_created_action", ["created_at", "action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_logs_actor_user_id"), ["actor_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_logs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_entity_id"), ["entity_id"], unique=False)

    op.create_table(
        "media_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("stored_name", sa.String(length=255), nullable=False),
        sa.Column("relative_path", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stored_name"),
    )
    with op.batch_alter_table("media_assets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_media_assets_sha256"), ["sha256"], unique=False)

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_refresh_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "telegram_connections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("BOT", "USER", name="connectionkind", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "AUTH_PENDING",
                "ACTIVE",
                "PAUSED",
                "ERROR",
                "REVOKED",
                name="connectionstatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("credentials_enc", sa.Text(), nullable=True),
        sa.Column("telegram_account_id", sa.BigInteger(), nullable=True),
        sa.Column("telegram_username", sa.String(length=64), nullable=True),
        sa.Column("telegram_display_name", sa.String(length=180), nullable=True),
        sa.Column("min_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("daily_cap", sa.Integer(), nullable=False),
        sa.Column("destination_cooldown_minutes", sa.Integer(), nullable=False),
        sa.Column("require_manual_approval", sa.Boolean(), nullable=False),
        sa.Column("stop_on_flood", sa.Boolean(), nullable=False),
        sa.Column("last_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("flood_blocked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("telegram_connections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_telegram_connections_status"), ["status"], unique=False
        )

    op.create_table(
        "destinations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("connection_id", sa.String(length=36), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("username", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "GROUP",
                "SUPERGROUP",
                "CHANNEL",
                "FORUM_TOPIC",
                name="destinationkind",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("validated", sa.Boolean(), nullable=False),
        sa.Column(
            "permission_status",
            sa.Enum(
                "UNVERIFIED",
                "CONFIRMED",
                "DENIED",
                name="permissionstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("permission_note", sa.Text(), nullable=True),
        sa.Column("rules_url", sa.String(length=1000), nullable=True),
        sa.Column("permission_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("permission_confirmed_by_id", sa.String(length=36), nullable=True),
        sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_allowed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["connection_id"], ["telegram_connections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["permission_confirmed_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "connection_id", "telegram_chat_id", "topic_id", name="uq_destination_chat_topic"
        ),
    )
    with op.batch_alter_table("destinations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_destination_enabled_permission", ["enabled", "permission_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_destinations_connection_id"), ["connection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_destinations_telegram_chat_id"), ["telegram_chat_id"], unique=False
        )

    op.create_table(
        "message_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "parse_mode",
            sa.Enum("PLAIN", "HTML", "MARKDOWN", name="parsemode", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("media_asset_id", sa.String(length=36), nullable=True),
        sa.Column("link_preview", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "telegram_auth_challenges",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("connection_id", sa.String(length=36), nullable=False),
        sa.Column("payload_enc", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "COMPLETED",
                "EXPIRED",
                "CANCELLED",
                name="challengestatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["connection_id"], ["telegram_connections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("telegram_auth_challenges", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_telegram_auth_challenges_connection_id"), ["connection_id"], unique=False
        )

    op.create_table(
        "campaigns",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("connection_id", sa.String(length=36), nullable=False),
        sa.Column("template_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SCHEDULED",
                "RUNNING",
                "PAUSED",
                "COMPLETED",
                "CANCELLED",
                "FAILED",
                name="campaignstatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "schedule_type",
            sa.Enum("ONCE", "DAILY", "WEEKLY", name="scheduletype", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("schedule_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone_name", sa.String(length=80), nullable=False),
        sa.Column("weekdays", sa.JSON(), nullable=False),
        sa.Column("spacing_seconds", sa.Integer(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("manual_approval_required", sa.Boolean(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_id", sa.String(length=36), nullable=True),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["telegram_connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["message_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.create_index("ix_campaign_due", ["status", "next_run_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_campaigns_connection_id"), ["connection_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_campaigns_next_run_at"), ["next_run_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_campaigns_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_campaigns_template_id"), ["template_id"], unique=False)

    op.create_table(
        "campaign_destinations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("destination_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("custom_body", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["destination_id"], ["destinations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "destination_id", name="uq_campaign_destination"),
    )
    with op.batch_alter_table("campaign_destinations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_campaign_destinations_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_campaign_destinations_destination_id"), ["destination_id"], unique=False
        )

    op.create_table(
        "campaign_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "COMPLETED",
                "PARTIAL",
                "FAILED",
                "CANCELLED",
                name="runstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("total_jobs", sa.Integer(), nullable=False),
        sa.Column("sent_jobs", sa.Integer(), nullable=False),
        sa.Column("failed_jobs", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "scheduled_for", name="uq_campaign_scheduled_run"),
    )
    with op.batch_alter_table("campaign_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_campaign_runs_campaign_id"), ["campaign_id"], unique=False
        )

    op.create_table(
        "delivery_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("connection_id", sa.String(length=36), nullable=False),
        sa.Column("destination_id", sa.String(length=36), nullable=False),
        sa.Column("template_id", sa.String(length=36), nullable=False),
        sa.Column("media_asset_id", sa.String(length=36), nullable=True),
        sa.Column("body_snapshot", sa.Text(), nullable=False),
        sa.Column(
            "parse_mode",
            sa.Enum("PLAIN", "HTML", "MARKDOWN", name="parsemode", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("link_preview", sa.Boolean(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "RETRY",
                "WAITING_REVIEW",
                "SENT",
                "FAILED",
                "CANCELLED",
                "SKIPPED",
                name="jobstatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=120), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("telegram_message_id", sa.String(length=100), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("safety_decision", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["telegram_connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["destinations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_assets.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["campaign_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["message_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_delivery_idempotency"),
    )
    with op.batch_alter_table("delivery_jobs", schema=None) as batch_op:
        batch_op.create_index("ix_delivery_due_status", ["status", "due_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_delivery_jobs_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_delivery_jobs_connection_id"), ["connection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_delivery_jobs_destination_id"), ["destination_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_delivery_jobs_due_at"), ["due_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_delivery_jobs_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_delivery_jobs_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_delivery_jobs_template_id"), ["template_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """Откатить this Alembic revision in dependency-safe schema order."""
    with op.batch_alter_table("delivery_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_delivery_jobs_template_id"))
        batch_op.drop_index(batch_op.f("ix_delivery_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_delivery_jobs_run_id"))
        batch_op.drop_index(batch_op.f("ix_delivery_jobs_due_at"))
        batch_op.drop_index(batch_op.f("ix_delivery_jobs_destination_id"))
        batch_op.drop_index(batch_op.f("ix_delivery_jobs_connection_id"))
        batch_op.drop_index(batch_op.f("ix_delivery_jobs_campaign_id"))
        batch_op.drop_index("ix_delivery_due_status")

    op.drop_table("delivery_jobs")
    with op.batch_alter_table("campaign_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaign_runs_campaign_id"))

    op.drop_table("campaign_runs")
    with op.batch_alter_table("campaign_destinations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaign_destinations_destination_id"))
        batch_op.drop_index(batch_op.f("ix_campaign_destinations_campaign_id"))

    op.drop_table("campaign_destinations")
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaigns_template_id"))
        batch_op.drop_index(batch_op.f("ix_campaigns_status"))
        batch_op.drop_index(batch_op.f("ix_campaigns_next_run_at"))
        batch_op.drop_index(batch_op.f("ix_campaigns_connection_id"))
        batch_op.drop_index("ix_campaign_due")

    op.drop_table("campaigns")
    with op.batch_alter_table("telegram_auth_challenges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_telegram_auth_challenges_connection_id"))

    op.drop_table("telegram_auth_challenges")
    op.drop_table("message_templates")
    with op.batch_alter_table("destinations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_destinations_telegram_chat_id"))
        batch_op.drop_index(batch_op.f("ix_destinations_connection_id"))
        batch_op.drop_index("ix_destination_enabled_permission")

    op.drop_table("destinations")
    with op.batch_alter_table("telegram_connections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_telegram_connections_status"))

    op.drop_table("telegram_connections")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_token_hash"))

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("media_assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_assets_sha256"))

    op.drop_table("media_assets")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_entity_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_actor_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))
        batch_op.drop_index("ix_audit_created_action")

    op.drop_table("audit_logs")
    op.drop_table("worker_heartbeats")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
